Repository TilmanGriesel/graphite, pull requests merged in 2024-11, with the labels that each got.

#38 feat: Introduce color-patcher tool
  README.md
  docs/screenshots/graphite_theme_patcher_demo.gif
  extras/theme-patcher/README.md
  extras/theme-patcher/graphite-theme-patcher.py
Labels: documentation, enhancement

#40 39 improve sections heading font
  src/template.yaml
  src/tokens_common.yaml
  themes/graphite-auto.yaml
  themes/graphite-light.yaml
  themes/graphite.yaml
  tools/rebuild_dev.sh
  tools/theme_assembler.py
Labels: improvement

#46 Revise theme patcher for development and expert usage
  README.md
  docs/screenshots/graphite_theme_patcher_demo.gif
  docs/screenshots/graphite_theme_patcher_demo_accent.gif
  docs/screenshots/graphite_theme_patcher_demo_advanced.gif
  extras/theme-patcher/README.md
  extras/theme-patcher/graphite-theme-patcher.py
Labels: extra, theme-patcher

#48 New Customization Feature: Min-Width of sections
  src/template.yaml
  src/tokens_common.yaml
  themes/graphite-auto.yaml
  themes/graphite-light.yaml
  themes/graphite.yaml
Labels: enhancement

#52 Choose label button has dark background and dark text
  .github/workflows/HACS_Action.yml
  .github/workflows/stale.yml
  .github/workflows/theme-verification.yaml
  .gitignore
  .pre-commit-config.yaml
  Makefile
  README.md
  src/about.yaml
  src/template.yaml
  src/tokens_common.yaml
  src/tokens_dark.yaml
  src/tokens_light.yaml
  themes/graphite-auto.yaml
  themes/graphite-light.yaml
  themes/graphite.yaml
  tools/rebuild_dev.sh
  tools/theme_assembler.py
Labels: bug, enhancement
